FROM node:14.0-stretch

# packages
COPY package.json package.json
RUN npm install

# source files
COPY data/trades.sqlite data/trades.sqlite
COPY trades.sqlite trades.sqlite
COPY src/ src/
COPY tsconfig.json tsconfig.json

CMD tsc src/pricefeed/index.ts && node src/pricefeed/index.ts